### ISSUE TITLE
http://current.geneontology.org/products/pages/downloads.html Page footer needs changing

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#184]
Hi, 

http://current.geneontology.org/products/pages/downloads.html

the footer says 
Copyright © 1999-2018 the Gene Ontology (CC-BY 4.0)

Needs to be changed to 2019 

It'd be nice to have the same footer as everywhere else, I suppose that's a little complicated ? 

Thanks, Pascale

**Comment by lpalbou** [comment]
Fixed: https://github.com/geneontology/go-site/commit/29ce467cbb86259ec5c47a37660cb09de2093649

It will appear on the website after the release since this is a static page produced by the pipeline and external to the go site (hence the different footer and styling).

Each dynamic page (e.g. stats or the wanted go-subsets) would need to be coded from scratch since we don't use framework. Still possible but let me know of the priority.

**Comment by pgaudet** [comment]
Do you know how much work that would be ?

**Comment by kltm** [comment]
@pgaudet We probably want to spin this out into a separate ticket/discussion. Currently, the downloads are generated in a separate location from the main site. There are a few different ways to make sure the footers are consistent (e.g. common templates).

**Comment by lpalbou** [comment]
If it's a 1:1 translation, about 2 days. It we want to make it exactly what we want, around 4-7 days between the discussions and iterative coding.

I liked for instance some of the features of this site and the easy access / description of each annotation set: https://git.dhimmel.com/gene-ontology/ , but this would require us to store additional files in the release.

**Comment by suzialeksander** [comment]
Couple more changes to footer:

- [x]  Footer link on "Helpdesk" currently 404s, should go to http://help.geneontology.org/ 

- [x] Footer link to RSS 404s, should be removed

- [x] Footer link to "acknowledgements page" currently 404s, should go to http://geneontology.org/docs/annotation-contributors/

Also, image on this page (logo in top left corner) is still broken.

**Comment by suzialeksander** [comment]
Footer and image issues resolved.  Will open new ticket for standardizing footers conversation.
