### ISSUE TITLE
Update Copyright

### ISSUE THREAD

**Issue by kltm** [geneontology/geneontology.github.io#197]
From @pgaudet 

```
Need to update the date to 2020...on the GO website @lpalbou
http://geneontology.org/
```

**Comment by lpalbou** [comment]
Done https://github.com/geneontology/geneontology.github.io/commit/8c29662a17741d2ec2014351707846fcdafc27b0

We also need to change the GAF download page footer: http://current.geneontology.org/products/pages/downloads.html

**Comment by pgaudet** [comment]
> We also need to change the GAF download page footer: http://current.geneontology.org/products/pages/downloads.html


Who should do that ? Please assign :)

**Comment by lpalbou** [comment]
I will do that during the day :) I can also check if I can easily update the date for the amigo page (your original ticket) but there is no automated deployment so @kltm will have to deploy it again.

**Comment by suzialeksander** [comment]
@lpalbou I saw this has changed in the code, but I'm still seeing 2019.  How long before this goes through?
